In [2]:
import numpy as np  #es para vectores y se nombra como np 
words = np.array(["nombre","pronombre","verbo","adverbvio","adjectivo","conjunccion","preposion"]) # asi se llama 
words


array(['nombre', 'pronombre', 'verbo', 'adverbvio', 'adjectivo',
       'conjunccion', 'preposion'], dtype='<U11')

In [3]:
words[3] #posicion 

'adverbvio'

In [13]:
words[0:] #Si se deja el espacio se carga de la posicion 1 hasta donde se acaba la lista

array(['nombre', 'pronombre', 'verbo', 'adverbvio', 'adjectivo',
       'conjunccion', 'preposion'], dtype='<U11')

In [33]:
words[0:6:2]  # posicion inical- posicion final- incremento 

array(['nombre', 'verbo', 'adjectivo'], dtype='<U11')

In [35]:
words[::-1]  #inverso de la lista 

array(['preposion', 'conjunccion', 'adjectivo', 'adverbvio', 'verbo',
       'pronombre', 'nombre'], dtype='<U11')

In [36]:
numbers = np.array([1,3,5.3])
numbers 

array([1. , 3. , 5.3])

In [37]:
numbers.sum() #llama a la funcion suma

9.3

In [38]:
numbers.size # dimension del vector 

3

In [39]:
numbers.mean() #media 

3.1

In [44]:
np.count_nonzero(numbers) #cuantas los numeros que no son 0


3

In [46]:
np.round(numbers [2]) #redondea los numeros  y si lo pones asi se rendondea la posicion de interes

5.0

In [52]:
numbers [2] = np.round( numbers[2]) # aca se actualiza el numero redondeando
numbers

array([1., 3., 5.])

In [58]:
numbers.sort()
numbers

array([1., 3., 5.])